# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool: mytestpool
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'testdocker'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'testdocker'
        repository: '$(Build.Repository.Name)'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    - task: Docker@2
      inputs:
        containerRegistry: 'testdocker'
        repository: '$(Build.Repository.Name)'
        command: 'push'
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: |
    #       $(tag)
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: buildAndPush
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: |
    #       $(tag)
    - task: CopyFiles@2
      inputs:
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1